window.esdocSearchIndex = [
  [
    "@aureooms/js-compare/src/proxy/attr/attr.js~attr",
    "function/index.html#static-function-attr",
    "<span>attr</span> <span class=\"search-result-import-path\">@aureooms/js-compare/src/proxy/attr/attr.js</span>",
    "function"
  ],
  [
    "@aureooms/js-compare/src/lexicographical/colexicographical.js~colexicographical",
    "function/index.html#static-function-colexicographical",
    "<span>colexicographical</span> <span class=\"search-result-import-path\">@aureooms/js-compare/src/lexicographical/colexicographical.js</span>",
    "function"
  ],
  [
    "@aureooms/js-compare/src/native/decreasing.js~decreasing",
    "function/index.html#static-function-decreasing",
    "<span>decreasing</span> <span class=\"search-result-import-path\">@aureooms/js-compare/src/native/decreasing.js</span>",
    "function"
  ],
  [
    "@aureooms/js-compare/src/lexicographical/fixed/fixedcolexicographical.js~fixedcolexicographical",
    "function/index.html#static-function-fixedcolexicographical",
    "<span>fixedcolexicographical</span> <span class=\"search-result-import-path\">@aureooms/js-compare/src/lexicographical/fixed/fixedcolexicographical.js</span>",
    "function"
  ],
  [
    "@aureooms/js-compare/src/lexicographical/fixed/fixedlexicographical.js~fixedlexicographical",
    "function/index.html#static-function-fixedlexicographical",
    "<span>fixedlexicographical</span> <span class=\"search-result-import-path\">@aureooms/js-compare/src/lexicographical/fixed/fixedlexicographical.js</span>",
    "function"
  ],
  [
    "@aureooms/js-compare/src/proxy/fn.js~fn",
    "function/index.html#static-function-fn",
    "<span>fn</span> <span class=\"search-result-import-path\">@aureooms/js-compare/src/proxy/fn.js</span>",
    "function"
  ],
  [
    "@aureooms/js-compare/src/native/increasing.js~increasing",
    "function/index.html#static-function-increasing",
    "<span>increasing</span> <span class=\"search-result-import-path\">@aureooms/js-compare/src/native/increasing.js</span>",
    "function"
  ],
  [
    "@aureooms/js-compare/src/proxy/attr/len.js~len",
    "function/index.html#static-function-len",
    "<span>len</span> <span class=\"search-result-import-path\">@aureooms/js-compare/src/proxy/attr/len.js</span>",
    "function"
  ],
  [
    "@aureooms/js-compare/src/lexicographical/lexicographical.js~lexicographical",
    "function/index.html#static-function-lexicographical",
    "<span>lexicographical</span> <span class=\"search-result-import-path\">@aureooms/js-compare/src/lexicographical/lexicographical.js</span>",
    "function"
  ],
  [
    "@aureooms/js-compare/src/lexicographical/quasi/quasicolexicographical.js~quasicolexicographical",
    "function/index.html#static-function-quasicolexicographical",
    "<span>quasicolexicographical</span> <span class=\"search-result-import-path\">@aureooms/js-compare/src/lexicographical/quasi/quasicolexicographical.js</span>",
    "function"
  ],
  [
    "@aureooms/js-compare/src/lexicographical/quasi/quasilexicographical.js~quasilexicographical",
    "function/index.html#static-function-quasilexicographical",
    "<span>quasilexicographical</span> <span class=\"search-result-import-path\">@aureooms/js-compare/src/lexicographical/quasi/quasilexicographical.js</span>",
    "function"
  ],
  [
    "@aureooms/js-compare/src/lexicographical/ranged/rangedcolexicographical.js~rangedcolexicographical",
    "function/index.html#static-function-rangedcolexicographical",
    "<span>rangedcolexicographical</span> <span class=\"search-result-import-path\">@aureooms/js-compare/src/lexicographical/ranged/rangedcolexicographical.js</span>",
    "function"
  ],
  [
    "@aureooms/js-compare/src/lexicographical/ranged/rangedlexicographical.js~rangedlexicographical",
    "function/index.html#static-function-rangedlexicographical",
    "<span>rangedlexicographical</span> <span class=\"search-result-import-path\">@aureooms/js-compare/src/lexicographical/ranged/rangedlexicographical.js</span>",
    "function"
  ],
  [
    "@aureooms/js-compare/src/tools/reverse.js~reverse",
    "function/index.html#static-function-reverse",
    "<span>reverse</span> <span class=\"search-result-import-path\">@aureooms/js-compare/src/tools/reverse.js</span>",
    "function"
  ],
  [
    "@aureooms/js-compare/src/tools/sign.js~sign",
    "function/index.html#static-function-sign",
    "<span>sign</span> <span class=\"search-result-import-path\">@aureooms/js-compare/src/tools/sign.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/lexicographical/colexicographical.js",
    "file/src/lexicographical/colexicographical.js.html",
    "src/lexicographical/colexicographical.js",
    "file"
  ],
  [
    "src/lexicographical/fixed/fixedcolexicographical.js",
    "file/src/lexicographical/fixed/fixedcolexicographical.js.html",
    "src/lexicographical/fixed/fixedcolexicographical.js",
    "file"
  ],
  [
    "src/lexicographical/fixed/fixedlexicographical.js",
    "file/src/lexicographical/fixed/fixedlexicographical.js.html",
    "src/lexicographical/fixed/fixedlexicographical.js",
    "file"
  ],
  [
    "src/lexicographical/lexicographical.js",
    "file/src/lexicographical/lexicographical.js.html",
    "src/lexicographical/lexicographical.js",
    "file"
  ],
  [
    "src/lexicographical/quasi/quasicolexicographical.js",
    "file/src/lexicographical/quasi/quasicolexicographical.js.html",
    "src/lexicographical/quasi/quasicolexicographical.js",
    "file"
  ],
  [
    "src/lexicographical/quasi/quasilexicographical.js",
    "file/src/lexicographical/quasi/quasilexicographical.js.html",
    "src/lexicographical/quasi/quasilexicographical.js",
    "file"
  ],
  [
    "src/lexicographical/ranged/rangedcolexicographical.js",
    "file/src/lexicographical/ranged/rangedcolexicographical.js.html",
    "src/lexicographical/ranged/rangedcolexicographical.js",
    "file"
  ],
  [
    "src/lexicographical/ranged/rangedlexicographical.js",
    "file/src/lexicographical/ranged/rangedlexicographical.js.html",
    "src/lexicographical/ranged/rangedlexicographical.js",
    "file"
  ],
  [
    "src/native/decreasing.js",
    "file/src/native/decreasing.js.html",
    "src/native/decreasing.js",
    "file"
  ],
  [
    "src/native/increasing.js",
    "file/src/native/increasing.js.html",
    "src/native/increasing.js",
    "file"
  ],
  [
    "src/proxy/attr/attr.js",
    "file/src/proxy/attr/attr.js.html",
    "src/proxy/attr/attr.js",
    "file"
  ],
  [
    "src/proxy/attr/len.js",
    "file/src/proxy/attr/len.js.html",
    "src/proxy/attr/len.js",
    "file"
  ],
  [
    "src/proxy/fn.js",
    "file/src/proxy/fn.js.html",
    "src/proxy/fn.js",
    "file"
  ],
  [
    "src/tools/reverse.js",
    "file/src/tools/reverse.js.html",
    "src/tools/reverse.js",
    "file"
  ],
  [
    "src/tools/sign.js",
    "file/src/tools/sign.js.html",
    "src/tools/sign.js",
    "file"
  ]
]